#!/usr/bin/env bash

# TODO: Prevent file in buffer from being overwritten

# script folder
sf=~/.config/suremark_pipe/buffer/
# address of server
host=SERVER
# remote destination folder (relative to remote home)
rf=.config/suremark/shared/suremark/pipe/
# remote filename base
fb=to_print

if [ -f "${sf}toprint.txt" ]; then
	# check if remote file exists
	i=99
	while scp "${host}":"${rf}""${fb}""${i}".txt /dev/null
	do
		i=$((${i}+1))
	done
	# copy file
	scp "${sf}toprint.txt" "${host}":"${rf}""${fb}""${i}".txt
	rm "${sf}toprint.txt"
fi

